site_name: Ones-OpenSDK
repo_url: https://github.com/AvizNetworks/ones-restapi
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: _media/favicon.ico
  features:
    - content.action.edit
    - content.code.copy
  markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  nav:
  - Home: index.md
  - ONES-API:
    - health-api : ones-api/health-api/health-api.md
    - health-client: ones-api/health-client/health-client.md
    - health-connect-methods: ones-api/health-connect-methods/health-connect-method.md
    - inventory-api : ones-api/inventory-api/inventory-api.md
    - inventory-client: ones-api/inventory-client/inventory-client.md
    - inventory-connect-methods: ones-api/inventory-connect-methods/inventory-connect-methods.md
    - topology-api: ones-api/topology-api/topology-api.md
    - topology-client: ones-api/topology-client/topology-client.md
    - topology-connect-method: ones-api/topology-connect-method/topology-connect-method.md
    - traffic-api: ones-api/traffic-api/traffic-api.md
    - traffic-client: ones-api/traffic-client/traffic-client.md
    - traffic-connect-method: ones-api/traffic-connect-method/traffic-connect-method.md



