site_name: ONES - PyAPI
repo_url: https://github.com/AvizNetworks/ones-pyapi
theme:
  name: readthedocs
  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to light mode
  favicon: _media/favicon.ico
  features:
    - content.action.edit
    - content.code.copy
  markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  nav:
    - ONES APIs: index.md
    - ONES APIs for Network Telemetry: Ones API For Network Telemetry/OnesAPIForNetworkTelemetry.md
    - Secured APIs for NetOps Monitoring: Ones API For Network Telemetry/Secured APIs For NetOps Monitoriing/SecureAPIsForNetOpsMonitoring.md
    - Streaming Telemetry: Ones API For Network Telemetry/Streaming Telemetry/StreamingTelemetry.md
    - Overview - ONES Agent:
      - ONES Agent: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/OnesAgent.md
      - GNMI Clients: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/gnmiClient.md
      - Data Models: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/data_models.md
      - System Resources: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/gnmic_open_config_path_system_resouerces.md
      - BGP control plane: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/bgp_controlplanes.md
      - LLDP neighbors: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/lldp_neighbours.md
      - Device interfaces: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/device_interface.md
      - Platform peripherals: Ones API For Network Telemetry/Streaming Telemetry/ONES AGENT/platform_peripherals.md

    - ONES APIs for Orchestration: Ones For Orchestration/OnesForOrchestration.md
    - Overview - Day 1 Orchestration:
      - Day 1 Orchestration: Ones For Orchestration/Day 1 Orchestration/Day1Orchestration.md
      - Day 2 NetOps: Ones For Orchestration/Day 1 Orchestration/index.md
    - ONES Integration with Prometheus: Ones Integration With Prometheus/index.md




  



